export enum CollaborationType {
  SPONSORSHIP = 'SPONSORSHIP',
  AMBASSADOR = 'AMBASSADOR',
  PRODUCT_COLLAB = 'PRODUCT_COLLAB',
  EVENT = 'EVENT',
  CONTENT_PARTNERSHIP = 'CONTENT_PARTNERSHIP',
  OTHER = 'OTHER',
}
