export enum Platform {
  INSTAGRAM = 'INSTAGRAM',
  FACEBOOK = 'FACEBOOK',
  TIKTOK = 'TIKTOK',
  YOUTUBE = 'YOUTUBE',
  SPOTIFY = 'SPOTIFY',
  APPLE_MUSIC = 'APPLE_MUSIC',
  SOUNDCLOUD = 'SOUNDCLOUD',
  BANDCAMP = 'BANDCAMP',
  BEATPORT = 'BEATPORT',
  OTHER = 'OTHER',
}
